name: Deploy

on:
  push:
    branches:
      - main
jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
            mongodb-version: '4.4.18'
            
      - name: Install API dependencies
        working-directory: ./api
        run: npm install

      - name: Run API tests
        working-directory: ./api
        run: npm run test