name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  run_generate:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install API dependencies
        working-directory: ./api
        run: npm install
      - name: Start server in development mode
        working-directory: ./api
        run: npm run dev
      - name: Install client dependencies
        working-directory: ./client
        run: npm install
      - name: Generate GraphQL types
        working-directory: ./client
        run: npm run generate
  
  build_client:
    needs: run_generate
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        working-directory: ./client
        run: npm run build
