# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  install_dependencies:
    runs-on: self-hosted
    steps:
      - name: Install API dependencies
        working-directory: ./api
        run: npm install
      - name: Install Client dependencies
        working-directory: ./client
        run: npm install
    
  start_dev_server:
    needs: install_dependencies
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Start server in development mode
        working-directory: ./api
        run: npm run dev &
  
  run_generate:
    needs: start_dev_server
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Generate GraphQL types
        working-directory: ./client
        run: npm run generate
  
  build_client:
    needs: run_generate
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        working-directory: ./client
        run: npm run build
