name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  run_generate:
    runs-on: self-hosted
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create API environment file
        working-directory: ./api
        run: |
          echo "${{ secrets.HTTPS }}" >> .env.development.local
          echo "${{ secrets.MONGODB_URI }}" >> .env.development.local
          echo "${{ secrets.PORT }}" >> .env.development.local
          echo "${{ secrets.SESSION_SECRET }}" >> .env.development.local
          echo "${{ secrets.SESSION_URI }}" >> .env.development.local
          echo "${{ secrets.WHITELISTED_DOMAINS }}" >> .env.development.local
      - name: Create client environment file
        working-directory: ./client
        run: |
          echo "${{ secrets.VITE_GRAPHQL_ENDPOINT }}" >> .env.development.local
      - name: Install API dependencies
        working-directory: ./api
        run: npm install
      - name: Start server in development mode
        working-directory: ./api
        run: npm run dev
      - name: Install client dependencies
        working-directory: ./client
        run: npm install
      - name: Generate GraphQL types
        working-directory: ./client
        run: npm run generate
  
  build_client:
    needs: run_generate
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        working-directory: ./client
        run: npm run build
